### ISSUE TITLE
.NET object activation

### ISSUE THREAD

**Issue by MarkPflug** [joelverhagen/joelverhagen.com#1]
Hi Joel.
I was reading through the .NET 6 performance blog that Stephen Toub published recently, and came across a section that reminded me of your object activation blog post. Apparently .NET 6 improves the performance of `new T()` for generic type activation. The relevant text is under the [reflection section](https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-6/#reflection), search for "Activator.CreateInstance" to find the relevant paragraph. I thought it might be interesting to compare whether your cached-emit-activator approach is still a performance win in .NET 6, or if the simpler `new T()` approach is now on-par.

**Comment by joelverhagen** [comment]
Thanks for the heads up. I think I'll just update the top of the blog post with a note linking to Toub's blog post. I'm too lazy to rerun the results and update the whole post.

**Comment by MarkPflug** [comment]
No worries. Just thought you might be interested, since you'd clearly spent some time researching this previously. Always nice when the idiomatic approach is also the fastest.
